### ISSUE TITLE
As a company, we need to provide a logistics or maintanence plan with pricing

### ISSUE THREAD

**Issue by AnthonyKoutroulis** [tigerjpg/cybersecurity#25]
We need to offer a maintenance plan with appropriate subscription cost.
Minimum 1 for First Sprint.
Add service options in comments here.

**Comment by theozornelas** [comment]
Tiger© Threat Protection
	This program detects and fights threats in real time. The programs tells if the data will be attacked or alerts about current attacks. Threat protection also gives the defense team the route of the attack, the IP address, and the location of the attacker. At the end it prints a report of all of the attacks and solutions that occurred in the moment.
Features:
•	Determines threat location (e.g., network vs. endpoint breach) and the extent of the threat in a minimum amount of time.
•	Continuously monitors web/enterprise email, removable media, and web downloads avoiding data losses and breaches. It blocks external sources from seeing or taking any files exchanged within the servers or a single server.
•	Delivers quick comprehensive visibility across multiple communication channels to identify threats. It does not slow or interrupts the flow of data, for the contrary, it deletes any malicious information so data can flow more effectively in between users.
•	Identifies in real-time external and internal threats for rapid mitigation.
•	Delivers superior contextual awareness reducing malware analysis time. It delivers messages across the board with malware threats status.
•	Interoperates with existing mail infrastructures reducing costs and down-time increasing efficiency.
Benefits:
•	Notifies Security and IT of risk protocol / compliance violations made on company endpoints.
•	Provides proprietary analytics and visualizations to enable quick prioritization of alerts.
•	Remediates the highest priority threats in real-time decreasing overall detection and escalation time.
•	It delivers messages to the administrators about any possible, upcoming, or current threats.
•	It emails accounts that at possible risk.

**Comment by theozornelas** [comment]
Tiger© Insider Threat
This advanced threat detection software performs a constant check in the data traffic without affecting the efficiency of the enterprise activity. Individual threats can be targeted for further investigation without the need to stop enterprises in the company. The programs generates a detailed report of the threat so it can be isolated and destroyed separately from other threats.
Features
•	Privacy protection
•	Universal SIEM (Security Information and Event Management) Integration
•	Log analysis. It has a secure Log in system that keeps checking even after the user has log on.
•	DVR-like replay. Replays any entry to the data base or any threatful event. 
•	Full activity capture. It records any activity done in the company, regardless of the user level.
•	Role-based access controls (RBAC)
Benefits
•	Provides incident replay including full event endpoint video recording and custom applications. It includes a log of all activities in a specific account.
•	Reduces dependency on technical expertise due to the simplicity of the program.
•	Enables safe and effective use of business and mission-critical technologies without any compatibility issues in between systems
•	Measures the impact of new and existing threats and compliance in real time
•	Scalable solution with highly stable agent. It does the most effective solution to any problem that might arise.
•	Detects policy violations hidden by encryption, including web traffic, e-mail and attachments without slowing the velocity of the traffic.
•	Promotes prompting and remediation for accidental data leak prevention preventing any identity theft or any possible leads to private data of the company.
•	Monitors offline activity for mobile and deliberately disconnected users if they are suspicious of illicit activity.

**Comment by theozornelas** [comment]
Tiger© Analytics
Allows examiners to investigate the data to create a picture of the activities that can be considered a threat to the system using the necessary protocols. It has an efficient search that does not la the transit in the network and collects all necessary data. It quickly responds to unusual patters in the system and from all sources.
Features:
•	Integrated geospatial, link, temporal and statistical visualizations enhance the accuracy.
•	Timeliness of intelligence by presenting massive amounts of data as one easy to digest picture.
•	Enables teams to gather the data from possible threats in order to create a solution.
•	Creates a map of the route of the malicious data that is leaking into the system.
Benefits
•	Minimized working data to prevent overload.
•	Decreases the need of IT infrastructure, thus minimizing maintenance cost.
•	Allows data to run faster thru the network, since it isolates data that may be harmful.

Tiger© Memory Integrity
This advanced system, analyzes volatile memory in Linux, Windows, and MacOs systems for any possible malware that may exist. It detects malware by using a combination of memory forensics and memory verification constantly. Enables an individual user to monitor a specific system and provides memory acquisition to determine the root of the problem.
Features
•	Supports all Linux distributions, 32- and 64-bit x86 systems providing flexibility and ease of implementation. Also supports versions of windows 7 and above, 32- and 64-bit x86 systems, and MacOsx Snow Leopard and above.
•	Provides a configurable scanning engine for automated scans of remote systems throughout an enterprise. That requires minimum to non, user skill.
•	Allows the integration of memory forensics into enterprise security information event management systems (SIEMS).
•	Includes an extensive collection of reference software (kernels and applications). It also has a tutorial for first time users and a gui that interacts with the user to implement the software.
•	Incorporates an easy-to-use user interface I to quickly assess and interpret results. It also outputs a reference page with all the locations affected in memory.
•	Delivers output in a structured data format (JSON) to facilitate analytics.
Benefits
•	Enables visibility into the state of systems software while executing in memory. 
•	Verifies the integrity of a remote system's kernel and the integrity of the executable code in all processes without doing a complete memory dump. 
•	Rapidly scans thousands of systems with hundreds of gigabytes of memory.
•	Delivers malware detection using an integrity verification approach to verify that all systems software running is known and unmodified to quickly identify threats.

**Comment by theozornelas** [comment]
Service Plan:
•	1 year warranty.
•	24/7 customer service.
•	24/7 technical service.
•	Replacement of equipment if damaged by product.
Maintenance Plan
•	Technical service is subject to charges:
	Visit: $10,000 USD
	Software Maintenance: +$5,000 USD
	Hardware Replacement: +2,000 USD
	Data Base Upgrade: +$7,000 USD
•	Software Upgrade:
	Latest Version of the program: $20,000 USD
	Add-on: $15,000 USD
•	Hardware Replacement: Only if affected by the security software.
Price 1 Year - Contract: 
Full Services and Coverage (all points above): $1,250,000 USD/year.  
Medium Package (Excludes free replacement of hardware and Data Base Upgrade: $1,200,000 USD/year.  
Base Package: (Excludes 24/7 Technical Support): $1,000,000 USD/year

**Comment by AnthonyKoutroulis** [comment]
These all look great, I'm okay with making this our product.
This should be close the First Sprint requirements. We can add more later if we want.
