### ISSUE TITLE
As a prospective customer, I would like to know what this company does and how.

### ISSUE THREAD

**Issue by ozyx** [tigerjpg/cybersecurity#3]

**Comment by theozornelas** [comment]
Tiger Inc.

Address: 3 Cheetah Avenue, Irvine, C.A 92614
Phone Number: 949 - 420 - 6969

Email Adress: TigerInc@Tiger.cjpg

Our Mission:
	This company was created by Ernest L. Cheetahiser in January, 1991. The
reason to create this company was to provide the public with solutions to
newly cyber security threats. We want to make the business world safe and reliable
in order to have a more stable market and economy.

What we do: 
	We create all kinds of olutions to cyberthreats. We create products
that prevent data leaks from within and outside the company. We also create
enviroments that fight cyber attackers and provide ways to know the source of the
issue so future attacks can be prevented. 
	The company has in it's mind that time is precious, that is why we provide
 the fastest and most reliable technical and costumer service in the market. We care
and protect our costumers better than ourselves.

How we do it:
	We use top of the edge technology for our systems as well as the most efficient
software. Our development team makes sure that the data we manage is always safe and
our software not interfiring with the traffic. Because we care our clients, we have 
meetings with company employees to find ways to improve our services and products.
